# Generated by Django 5.1 on 2026-03-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comprimento (m)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largura (m)')),
                ('details', models.TextField(blank=True, default='', verbose_name='Detalhes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quotes/photos/', verbose_name='Foto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('language', models.CharField(default='pt', max_length=5, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
