# Generated by Django 5.1 on 2026-03-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Final (€)'),
        ),
    ]
