# Generated by Django 5.1 on 2026-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pt', models.CharField(max_length=100, verbose_name='Nome (PT)')),
                ('name_br', models.CharField(max_length=100, verbose_name='Nome (BR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nome (EN)')),
                ('image_url', models.URLField(verbose_name='URL da Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requires_dimensions', models.BooleanField(default=False, verbose_name='Requer Medidas')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['sort_order'],
            },
        ),
    ]
