# Generated by Django 5.1 on 2026-03-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Base (€)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Mínimo (€)'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(choices=[('per_piece', 'Por Peça'), ('per_sqm', 'Por m²')], default='per_piece', max_length=10, verbose_name='Unidade de Preço'),
        ),
    ]
